version: '3'

volumes:
  postgres:
    driver: local

services:

  database:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: HomeApplianceStoreDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  homeappliancestore-api:
    image: homeappliancestore
    restart: always
    build:
      context: ./HomeApplianceStore.API
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 5002:80