// <auto-generated />
using System;
using HomeApplianceStore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HomeApplianceStore.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191108102516_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Client", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Guid");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Goods", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssemblyPlace");

                    b.Property<bool>("Availability");

                    b.Property<string>("Manufacturer");

                    b.Property<Guid?>("OrderGuid");

                    b.Property<int>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("Type");

                    b.HasKey("Guid");

                    b.HasIndex("OrderGuid");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Order", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ClientGuid");

                    b.Property<string>("CurrentStatus");

                    b.Property<DateTime>("DateTimeOrder");

                    b.Property<string>("DeliveryTerms");

                    b.Property<int>("TotalCost");

                    b.HasKey("Guid");

                    b.HasIndex("ClientGuid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.SpecificationValue", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Guid");

                    b.ToTable("SpecificationValues");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Specifications", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GoodsGuid");

                    b.Property<string>("SpecificationName");

                    b.Property<Guid>("ValueGuid");

                    b.HasKey("Guid");

                    b.HasIndex("GoodsGuid");

                    b.HasIndex("ValueGuid");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Goods", b =>
                {
                    b.HasOne("HomeApplianceStore.Database.Models.Order")
                        .WithMany("Goods")
                        .HasForeignKey("OrderGuid");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Order", b =>
                {
                    b.HasOne("HomeApplianceStore.Database.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientGuid");
                });

            modelBuilder.Entity("HomeApplianceStore.Database.Models.Specifications", b =>
                {
                    b.HasOne("HomeApplianceStore.Database.Models.Goods")
                        .WithMany("Specifications")
                        .HasForeignKey("GoodsGuid");

                    b.HasOne("HomeApplianceStore.Database.Models.SpecificationValue", "SpecificationValue")
                        .WithMany()
                        .HasForeignKey("ValueGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
